<div class="modal fade" id="addpeca" tabindex="-1" role="dialog" aria-labelledby="addpecaTitulo" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <form action="<?= $v_page_url ?>addPeca" method="post">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle"><i class="fa fa-plus fa-1x"></i> Peça</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                    <div class="form-group">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12" for="peca">Peça: <span style="color: red;"> </span></label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <input type="hidden" value="<?= $v_entity->getId(); ?>" name="id_folha">
                            <input type="text" id="peca" name="peca" class="form-control" required>
                        </div>
                        <label class="control-label col-md-12 col-sm-12 col-xs-12" for="quantidade">Quant.: <span style="color: red;"> </span></label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <input type="number" id="quantidade" name="quantidade" class="form-control" required>
                        </div>
                        <label class="control-label col-md-12 col-sm-12 col-xs-12" for="preco">Preço: <span style="color: red;"> </span></label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <input type="number" id="preco" name="preco" class="form-control" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class=" btn btn-success">Adicionar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </form>

    </div>
</div>