<div class="modal fade" id="addacessorio" tabindex="-1" role="dialog" aria-labelledby="addacessorioTitulo" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <form action="<?= $v_page_url ?>addAcessorio" method="post">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle"><i class="fa fa-plus fa-1x"></i> Acessório</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                    <div class="form-group">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12" for="actual">Acessório: <span style="color: red;"> </span></label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <input type="hidden" value="<?= $v_entity->getId(); ?>" name="id_folha">
                            <select id="acessorio" name="acessorio" class="form-control" required>
                                <option value="" required> Selecionar Acessório </option>
                                <?php
                                $v_acessorios = (isset($v_acessorios) ? ($v_acessorios) : (array()));
                                foreach ($v_acessorios as $acessorio) {
                                    echo '<option value="' . $acessorio->getId() . '">' . $acessorio->getNome() . '</option> ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class=" btn btn-success">Adicionar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </form>

    </div>
</div>