<a class="btn btn-primary" data-toggle="modal" data-target="#adddocumento" style="cursor:pointer;"><i class="fa fa-plus m-right-xs"></i> Documentos</a>
<hr>
<table id="example2" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Documento</th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        <?php
            if (isset($v_documentosFolha)) {
                if (empty($v_documentosFolha)) {
                ?>
        <div class="alert alert-danger">
            <strong><span class="fa fa-info"></span></strong> Folha de Obra sem Documento.
        </div>
        <?php
                }
                $cont = 0;
                foreach ($v_documentosFolha as $documento) {
                ?>
        <tr>
            <td><?php echo (++$cont);?></td>
            <td><?= $documento->getDocumento()->getTipoDoc()?></td>
            <td style="text-align:center;">
            <a href="<?=$v_page_url ?>eliminarDocumento/<?php echo base64_encode("id_documento") . '/' . base64_encode($documento->getId()) ?>/<?php echo base64_encode("id") . '/' . base64_encode($v_entity->getId()) ?>/" class="btn btn-danger btn-circle" title="Remover">X</a>
            </td>
        </tr>
        <?php }
    } ?>
    </tbody>
</table>