<!DOCTYPE HTML>
<html>
	<head>
		<?php
        echo' <title>' . $v_title_page . '</title>';
        include_once 'app/views/public/adm_cabecalho.phtml';
        ?>
		<body>
			<div id="wrapper">
				<!----->
				<nav class="navbar-default navbar-static-top" role="navigation">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<h1>
							<a class="navbar-brand" href="#">EDITOR <span class="fa fa-edit"></span></a>
						</h1>
                    </div>
                    <?php include_once 'app/views/public/pesquisar.phtml'; ?>
					
					<!-- Brand and toggle get grouped for better mobile display -->
					<!-- Menu TOPO -->
					<?php include_once 'app/views/public/menu_topo.phtml'; ?>
					<!-- /.Menu TOPO -->
					<div class="clearfix"></div>
					<div class="navbar-default sidebar" role="navigation">
                        <!-- Menu PRINCIPAL -->
                        <?php include_once 'app/views/public/menu/menu.phtml'; ?>
                        <!-- / Menu PRINCIPAL -->
					</div>
				</nav>
							<div id="page-wrapper" class="gray-bg dashbard-1">
								<div class="content-main">
									<!--banner-->
									<div class="banner">
										<h2>
											<a href="<?php echo $v_page_url;?>">Home</a>
											<!--
											<i class="fa fa-angle-right"></i><span>Blank</span>
											-->
										</h2>
									</div>
									<!--//banner-->
									<!--faq-->
									<div class="blank">
										<div class="blank-page">
										<?php
											if(isset($v_mensagem))
											{
												echo $v_mensagem;
											}
											else
											{
												?>
												A página que solicitou não existe ou não tem permissão para visualizar esta informação.
												<?php
											}
											?>
										</div>
									</div>
									<!--//faq-->
									<!---->
                                    <!-- footer -->
                                    <?php include_once 'app/views/public/adm_footer.phtml'; ?>
                                    <!-- /footer -->
								</div>
							</div>
            <div class="clearfix"></div>
            </div>
            <!---->
			<!--scrolling js-->
			<?php include_once 'app/views/public/adm_javascript.phtml'; ?>
            <!--//scrolling js-->
        </body>
</html>

