<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
    include_once 'app/views/public/adm/selectorCSS.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context;?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->
            <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title"></h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" id="formMarca" method="POST" action="<?= $v_page_url;?>registar">
                <div class="card-body">
                  <div class="form-group">
                    <label for="veiculo-<?= $v_page_context;?>">Veículo</label>
                    <select id="veiculo-<?= $v_page_context;?>" name="veiculo" class="form-control select2" required>
                    <option value="" required> --- </option>
                    <?php
                      $v_veiculos = (isset($v_veiculos) ? ($v_veiculos) : (array()));
                        foreach ($v_veiculos as $veiculo) {
                          echo '<option value="' . $veiculo->getId() . '">'. $veiculo->getMarca()->getNome() . ' - '.$veiculo->getModelo().' - '.$veiculo->getMatricula().'</option> ';
                        }
                    ?>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="area-servico">Área de serviço</label>
                    <input type="text" name="area" class="form-control" id="area-servico" placeholder="Área de serviço" required>
                  </div>
                  <div class="form-group">
                    <label for="km">Quilometragem (Km/h)</label>
                    <input type="number" name="km" min="0" class="form-control" id="km" placeholder="Quilometragem (Km/h)" required>
                  </div>
                  <div class="form-group">
                    <label for="avaria">Avaria</label>
                    <textarea name="avaria" rows="2" class="form-control" id="avaria" placeholder="Avaria"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="reparacao">Reparação</label>
                    <textarea name="reparacao" rows="2" class="form-control" id="reparacao" placeholder="Reparação"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="km">Data de entrada</label>
                    <input type="date" name="entrada" class="form-control" id="entrada" placeholder="Data de entrada" required>
                  </div>
                  <div class="form-group">
                    <label for="km">Data de saída</label>
                    <input type="date" name="saida" class="form-control" id="saida" placeholder="Data de saída" required>
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i
                        class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                  <button type="submit" class="btn btn-primary">Gravar</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
            
            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>
    
  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
    include_once 'app/views/public/adm/selectorJS.phtml';
  ?>
  <script type="text/javascript">
$(document).ready(function () {
  $.validator.setDefaults({
  });
  $('#formMarca').validate({
    rules: {
      nome: {
        required: true
      },
      descricao: {
        required: true,
        minlength: 10
      },
      terms: {
        required: true
      },
    },
    messages: {
      nome: {
        required: "Por favor, insira o nome da marca"
      },
      descricao: {
        required: "É necessário que descreva a marca para melhor detalhes",
        minlength: "Descrição é muito curtaa. Deve ter mais de 10 caracteres."
      }
      /*,
      terms: "Please accept our terms"*/
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
});
function voltar() {
  window.history.back();
}
</script>
</body>
</html>