<!DOCTYPE html>
<html lang="pt-br">

<head>
    <?php
    include_once 'app/views/public/default/head.phtml';
    ?>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <?php
    include_once 'app/views/public/default/header.phtml';
    ?>
    <!-- Header End -->

    <!-- Hero Section Begin -->

    <!-- Hero Section End -->

    <!-- Counter Section Begin -->
    <section class="counter-section bg-gradient">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="counter-text">
                        <span>FestiAngola 2021</span>
                        <h3>Festival Nacional <br />da Canção Patriótica</h3>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="cd-timer" id="countdown">
                        <div class="cd-item">
                            <span>40</span>
                            <p>Dias</p>
                        </div>
                        <div class="cd-item">
                            <span>18</span>
                            <p>Horas</p>
                        </div>
                        <div class="cd-item">
                            <span>46</span>
                            <p>Minutos</p>
                        </div>
                        <div class="cd-item">
                            <span>32</span>
                            <p>Segundos</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Counter Section End -->

    <!-- Home About Section Begin -->
    <section class="home-about-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="ha-pic">
                        <img src="https://festiangola.co.ao/web-files/assets/img/i-about.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="ha-text">
                        <h2 style="color:#f00;">Inscrições para Festival Nacional da Canção Patriótica estão encerradas.</h2>
                        <h3>As inscrições decorreram entre de 30 de Julho á 31 de Agosto de 2021.</h3>
                        <h3 style="padding-top:30px;">A equipa do <b>FestAngola 2021</b> agradece a todos os candidatos.</h3>
                        <div class="row">
                            <div class="col-lg-12">
                                
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Home About Section End -->

    <!-- Contact Section Begin -->
    <?php
    include_once 'app/views/public/default/contact.phtml';
    ?>
    <!-- // Contact Section End -->

    <!-- Footer Section Begin -->
    <?php
    include_once 'app/views/public/default/foot.phtml';
    ?>
    <!-- // Footer Section End -->

    <!-- Js Plugins -->
    <?php
    include_once 'app/views/public/default/javascript.phtml';
    ?>
    <!-- // Js Plugins -->
</body>

</html>