<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page; ?></title>

  <?php
  include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
    include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
      include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context; ?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <form role="form" id="formCandidato" method="POST" action="<?= $v_page_url; ?>actualizar">
            <div class="row">
              <!-- / Corpo da página INÍCIO -->

              <div class="col-6">

                <div class="card">

                  <div class="card-body">
                    <div class="form-group">
                      <label for="numero-candidato">N.º do Candidato</label>
                      <input type="text" name="numero-candidato" class="form-control" id="numero-candidato" placeholder="Número do Candidato" value="<?= $v_entity->getNumero() ?>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="nome-candidato">Nome do Candidato</label>
                      <input type="text" name="nome" class="form-control" id="nome-candidato" placeholder="Nome do Candidato" value="<?= $v_entity->getNome() ?>">
                      <input type="hidden" name="id_candidato" value="<?= $v_entity->getId() ?>">
                    </div>
                    <div class="form-group">
                      <label for="bi-candidato">N.º do Bilhete de Identidade</label>
                      <input type="text" name="bi" class="form-control" id="bi-candidato" placeholder="N.º do Bilhete de Identidade" value="<?= $v_entity->getBi() ?>">
                    </div>
                    <div class="form-group">
                      <label for="genero-candidato">Género</label>
                      <select type="text" name="genero" class="form-control" id="genero-candidato">
                        <option value=""> - Género - </option>
                        <?php
                        echo '<option value="' . Geral::CONS_GENERO_FEMININO . '" ' . (Geral::CONS_GENERO_FEMININO == $v_entity->getGenero() ? 'selected' : '') . '>Feminino</option> ';
                        echo '<option value="' . Geral::CONS_GENERO_MASCULINO . '" ' . (Geral::CONS_GENERO_MASCULINO == $v_entity->getGenero() ? 'selected' : '') . '>Masculino</option> ';
                        ?>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="nascimento-candidato">Data de nascimento</label>
                      <input type="date" name="nascimento" class="form-control" id="nascimento-candidato" placeholder="Data de nascimento" value="<?= $v_entity->getNascimento() ?>">
                    </div>
                    <div class="form-group">
                      <label for="provincia-candidato">Província</label>
                      <select type="text" name="provincia" class="form-control" id="provincia-candidato">
                        <option value=""> - Provincia - </option>
                        <?php
                        $v_provincias = (isset($v_provincias) ? ($v_provincias) : (array()));
                        foreach ($v_provincias as $provincia) {
                          echo '<option value="' . $provincia->getId() . '" ' . ($provincia->getId() == $v_entity->getProvincia()->getId() ? 'selected' : '') . '>' . ($provincia->getNome()) . '</option> ';
                        }
                        ?>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="telefone-candidato">Telefone</label>
                      <input type="number" name="telefone" class="form-control" id="telefone-candidato" placeholder="Telefone" value="<?= $v_entity->getTelefone() ?>">
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <!--<div class="card-footer">
                  <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context; ?></button>
                </div>-->
                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                      <button type="submit" class="btn btn-primary">Actualizar <?= $v_page_context; ?></button>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-6">
                <div class="card">
                  <div class="card-body">
                      
                      <div class="form-group">
                      <label for="estilo-candidato">Estilo Musical</label>
                      <select type="text" name="estilo" class="form-control" id="estilo-candidato">
                        <option value=""> - Estilo Musical - </option>
                        <?php
                        $v_estilos = (isset($v_estilos) ? ($v_estilos) : (array()));
                        foreach ($v_estilos as $estilo) {
                          echo '<option value="' . $estilo->getId() . '" ' . ($estilo->getId() == $v_entity->getEstilo()->getId() ? 'selected' : '') . '>' . ($estilo->getNome()) . '</option> ';
                        }
                        ?>
                      </select>
                    </div>
                    
                    <div class="form-group">
                      <label for="link-candidato">Link da música</label><br>
                      <a href="<?= $v_entity->getLink() ?>" target="_blank">Descarregar a música</a>
                    </div>
                    
                    <div class="form-group">
                      <label for="link-candidato">Data de Inscrição</label><br>
                      <?= $v_entity->getData() ?>
                    </div>
                      
                  </div>
                </div>
              </div>
              <!-- / Corpo da página FIM -->
            </div>
          </form>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
  include_once 'app/views/public/adm/javascript.phtml';
  include_once 'app/views/public/adm/datatables.phtml';
  ?>
  <script type="text/javascript">
    $(document).ready(function() {
      $.validator.setDefaults({});
      $('#formCandidato').validate({
        rules: {
          nome: {
            required: true
          },
          bi: {
            required: true,
            minlength: 12
          },
          nascimento: {
            required: true
          },
          genero: {
            required: true
          },
          provincia: {
            required: true
          },
          telefone: {
            required: true,
            maxlength: 9
          },
          estilo: {
            required: true
          },
          link: {
            required: true
          },
          terms: {
            required: true
          },
        },
        messages: {
          nome: {
            required: "Por favor, insira o nome do candidato."
          },
          bi: {
            required: "Por favor, insira o número do bilhete de identidade.",
            minlength: "O número do bilhete de identidade é muito curto. Deve ter mais de 12 caracteres."
          },
          nascimento: {
            required: "Por favor, insira a data de nascimento."
          },
          genero: {
            required: "Por favor, informe o género."
          },
          provincia: {
            required: "Por favor, informe a província."
          },
          telefone: {
            required: "Por favor, informe o seu contacto telefónico.",
            maxlength: "O número de telefone só pode ter 9 dígitos."
          },
          estilo: {
            required: "Por favor, selecione o estilo da música."
          },
          link: {
            required: "Por favor, insira o link onde podemos encontrar a música."
          }
          /*,
          terms: "Please accept our terms"*/
        },
        errorElement: 'span',
        errorPlacement: function(error, element) {
          error.addClass('invalid-feedback');
          element.closest('.form-group').append(error);
        },
        highlight: function(element, errorClass, validClass) {
          $(element).addClass('is-invalid');
        },
        unhighlight: function(element, errorClass, validClass) {
          $(element).removeClass('is-invalid');
        }
      });
    });

    function voltar() {
      window.history.back();
    }
  </script>
</body>

</html>