<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page; ?></title>

  <?php
  include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
    include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
      include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context; ?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title"></h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" id="formCandidato" method="POST" action="<?= $v_page_url; ?>registar">
                  <div class="card-body">
                    <div class="form-group">
                      <label for="nome-candidato">Nome do candidato ou Grupo</label>
                      <input type="text" name="nome" class="form-control" id="nome-candidato" placeholder="Nome do candidato ou Grupo">
                    </div>
                    <div class="form-group">
                      <label for="bi-candidato">N. Bilhete de Identidade do candidato ou líder do grupo</label>
                      <input type="text" name="bi" class="form-control" id="bi-candidato" placeholder="N. Bilhete de Identidade do candidato ou líder do grupo">
                    </div>
                    <div class="form-group">
                      <label for="nascimento-candidato">Data de nascimento</label>
                      <input type="date" name="nascimento" class="form-control" id="nascimento-candidato" placeholder="Data de nascimento">
                    </div>
                    <div class="form-group">
                      <label for="genero-candidato">Género</label>
                      <select type="text" name="genero" class="form-control" id="genero-candidato">
                        <option value=""> - Género - </option>
                        <option value="<?= Geral::CONS_GENERO_FEMININO?>">Feminino</option>
                        <option value="<?= Geral::CONS_GENERO_MASCULINO?>">Masculino</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="provincia-candidato">Província</label>
                      <select type="text" name="provincia" class="form-control" id="provincia-candidato">
                        <option value=""> - Provincia - </option>
                        <?php
                        $v_provincias = (isset($v_provincias) ? ($v_provincias) : (array()));
                        foreach ($v_provincias as $provincia) {
                          echo '<option value="' . $provincia->getId() . '">' . ($provincia->getNome()) . '</option> ';
                        }
                        ?>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="telefone-candidato">Telefone</label>
                      <input type="number" name="telefone" class="form-control" id="telefone-candidato" placeholder="Telefone">
                    </div>
                    <div class="form-group">
                      <label for="estilo-candidato">Estilo Musical</label>
                      <select type="text" name="estilo" class="form-control" id="estilo-candidato">
                        <option value=""> - Estilo Musical - </option>
                        <?php
                        $v_estilos = (isset($v_estilos) ? ($v_estilos) : (array()));
                        foreach ($v_estilos as $estilo) {
                          echo '<option value="' . $estilo->getId() . '">' . ($estilo->getNome()) . '</option> ';
                        }
                        ?>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="link-candidato">Link da música</label>
                      <input type="text" name="link" class="form-control" id="link-candidato" placeholder="https://">
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                    <button type="submit" class="btn btn-primary">Gravar</button>
                  </div>
                </form>
              </div>
              <!-- /.card -->
            </div>

            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
  include_once 'app/views/public/adm/javascript.phtml';
  include_once 'app/views/public/adm/datatables.phtml';
  ?>
  <script type="text/javascript">
    $(document).ready(function() {
      $.validator.setDefaults({});
      $('#formCandidato').validate({
        rules: {
          nome: {
            required: true
          },
          bi: {
            required: true,
            minlength: 12
          },
          nascimento: {
            required: true
          },
          genero: {
            required: true
          },
          provincia: {
            required: true
          },
          telefone: {
            required: true,
            maxlength: 9
          },
          estilo: {
            required: true
          },
          link: {
            required: true
          },
          terms: {
            required: true
          },
        },
        messages: {
          nome: {
            required: "Por favor, insira o nome do candidato ou Grupo."
          },
          bi: {
            required: "Por favor, insira o número Bilhete de Identidade do candidato ou líder do grupo.",
            minlength: "O número do bilhete de identidade é muito curto. Deve ter mais de 12 caracteres."
          },
          nascimento: {
            required: "Por favor, insira a data de nascimento."
          },
          genero: {
            required: "Por favor, informe o género."
          },
          provincia: {
            required: "Por favor, informe a província."
          },
          telefone: {
            required: "Por favor, informe o seu contacto telefónico.",
            maxlength: "O número de telefone só pode ter 9 dígitos."
          },
          estilo: {
            required: "Por favor, selecione o estilo da música."
          },
          link: {
            required: "Por favor, insira o link onde podemos encontrar a música."
          }
          /*,
          terms: "Please accept our terms"*/
        },
        errorElement: 'span',
        errorPlacement: function(error, element) {
          error.addClass('invalid-feedback');
          element.closest('.form-group').append(error);
        },
        highlight: function(element, errorClass, validClass) {
          $(element).addClass('is-invalid');
        },
        unhighlight: function(element, errorClass, validClass) {
          $(element).removeClass('is-invalid');
        }
      });
    });

    function voltar() {
      window.history.back();
    }
  </script>
</body>

</html>