<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page; ?></title>

  <?php
  include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
    include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
      include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context; ?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->

            <div class="col-6">
              <div class="card">

                <form role="form" id="formCandidato" method="POST" action="<?= $v_page_url; ?>registar">
                  <div class="card-body">
                    <div class="form-group">
                      <label for="numero-candidato">N.º do Candidato</label>
                      <input type="text" name="numero-candidato" class="form-control" id="numero-candidato" placeholder="Número do Candidato" value="<?= $v_entity->getNumero() ?>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="nome-candidato">Nome do Candidato</label>
                      <input type="text" name="nome" class="form-control" id="nome-candidato" placeholder="Nome do Candidato" value="<?= $v_entity->getNome() ?>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="bi-candidato">N.º do Bilhete de Identidade</label>
                      <input type="text" name="bi" class="form-control" id="bi-candidato" placeholder="N.º do Bilhete de Identidade" value="<?= $v_entity->getBi() ?>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="email-candidato">E-mail</label>
                      <input type="email" name="email" class="form-control" id="email-candidato" placeholder="E-mail" value="<?= $v_entity->getEmail() ?>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="genero-candidato">Género</label>
                      <select type="text" name="genero" class="form-control" id="genero-candidato" disabled>
                        <option value=""> - Género - </option>
                        <option value="Feminino">Feminino</option>
                        <option value="Masculino">Masculino</option>
                        <?php
                        echo '<option value="' . Geral::CONS_GENERO_FEMININO . '" ' . (Geral::CONS_GENERO_FEMININO == $v_entity->getGenero() ? 'selected' : '') . '>Feminino</option> ';
                        echo '<option value="' . Geral::CONS_GENERO_MASCULINO . '" ' . (Geral::CONS_GENERO_MASCULINO == $v_entity->getGenero() ? 'selected' : '') . '>Masculino</option> ';
                        ?>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="nascimento-candidato">Data de nascimento</label>
                      <input type="date" name="nascimento" class="form-control" id="nascimento-candidato" placeholder="Data de nascimento" value="<?= $v_entity->getNascimento() ?>" disabled>
                    </div>
                    <div class="form-group">
                      <label for="provincia-candidato">Província</label>
                      <select type="text" name="provincia" class="form-control" id="provincia-candidato" disabled>
                        <option value=""> - Provincia - </option>
                        <?php
                        $v_provincias = (isset($v_provincias) ? ($v_provincias) : (array()));
                        foreach ($v_provincias as $provincia) {
                          echo '<option value="' . $provincia->getId() . '" ' . ($provincia->getId() == $v_entity->getProvincia()->getId() ? 'selected' : '') . '>' . ($provincia->getNome()) . '</option> ';
                        }
                        ?>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="telefone-candidato">Telefone</label>
                      <input type="number" name="telefone" class="form-control" id="telefone-candidato" placeholder="Telefone" value="<?= $v_entity->getTelefone() ?>" disabled>
                    </div>
                    
                  </div>
                  <!-- /.card-body -->
                  <!--<div class="card-footer">
                  <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context; ?></button>
                </div>-->
                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                      <a href="<?= $v_page_url ?>editar/<?php echo base64_encode("id") . '/' . base64_encode($v_entity->getId()) ?>" class="btn btn-warning btn-circle" title="Editar"><i class="fa fa-edit"></i></a>
                      <a href="<?= $v_page_url ?>eliminar/<?php echo base64_encode("id") . '/' . base64_encode($v_entity->getId()) ?>" class="btn btn-danger btn-circle" title="Eliminar"><i class="fa fa-trash"></i></a>
                    </div>
                  </div>
                </form>
              </div>
            </div>

            <div class="col-6">
              <div class="card">
                <div class="card-body">
                    
                    <div class="form-group">
                      <label for="estilo-candidato">Estilo Musical</label>
                      <select type="text" name="estilo" class="form-control" id="estilo-candidato" disabled>
                        <option value=""> - Estilo Musical - </option>
                        <?php
                        $v_estilos = (isset($v_estilos) ? ($v_estilos) : (array()));
                        foreach ($v_estilos as $estilo) {
                          echo '<option value="' . $estilo->getId() . '" ' . ($estilo->getId() == $v_entity->getEstilo()->getId() ? 'selected' : '') . '>' . ($estilo->getNome()) . '</option> ';
                        }
                        ?>
                      </select>
                    </div>
                    
                    <div class="form-group">
                      <label for="link-candidato">Link da música</label><br>
                      <a href="<?= $v_entity->getLink() ?>" target="_blank">Descarregar a música</a>
                    </div>
                    
                    <div class="form-group">
                      <label for="link-candidato">Data de Inscrição</label><br>
                      <?= $v_entity->getData() ?>
                    </div>
                    
                </div>

              </div>
            </div>

            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
  include_once 'app/views/public/adm/javascript.phtml';
  include_once 'app/views/public/adm/datatables.phtml';
  ?>
</body>

</html>