<!DOCTYPE html>
<html lang="pt-br">

<head>
    <?php
    include_once 'app/views/public/default/head.phtml';
    ?>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <?php
      include_once 'app/views/public/default/header.phtml';
    ?>
    <!-- // Header End -->
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Esteja a vontade para contactar</h2>
                        <div class="bt-option">
                            <a href="/festival/Home/">Início</a>
                            <span>Contactos</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Contact Top Content Section Begin -->
    <section class="contact-content-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="cc-text set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/contact-content-bg.jpg">
                        <div class="row">
                            <div class="col-lg-8 offset-lg-4">
                                <div class="section-title">
                                    <h2>Endereço</h2>
                                    <p>Urbanização Boa Vida</p>
                                </div>
                                <div class="cs-text">
                                    <div class="ct-address">
                                        <span>Endereço:</span>
                                        <p>Urbanização Boa Vida, Via Expressa <br />Luanda</p>
                                    </div>
                                    <ul>
                                        <li>
                                            <span>Telefones:</span>
                                            +244 923 698 943 &bull; +244 944 692 347
                                        </li>
                                        <li>
                                            <span>Email:</span>
                                            geral@festiangola.co.ao
                                        </li>
                                    </ul>
                                    <div class="ct-links">
                                        <span>Website:</span>
                                        <p>https://festiangola.co.ao</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="cc-map">
                        <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.970528513714!2d13.214864114786193!3d-8.974858893558443!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1a521f28dbf07e05%3A0xc1b45c57d9661cff!2sUrbaniza%C3%A7%C3%A3o%20Boa%20Vida!5e0!3m2!1spt-PT!2sao!4v1627476924930!5m2!1spt-PT!2sao"
                            height="580" style="border:0;" allowfullscreen=""></iframe>
                        <div class="map-hover">
                            <i class="fa fa-map-marker"></i>
                            <div class="map-hover-inner">
                                <h5>Urbanização Boa Vida</h5>
                                <p>Luanda</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Top Content Section End -->

    <!-- Contact Form Section Begin -->
    <!--
    <section class="contact-from-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Contacto por email</h2>
                        <p></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form action="#" class="comment-form contact-form">
                        <div class="row">
                            <div class="col-lg-4">
                                <input type="text" placeholder="Nome" required>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" placeholder="Email" required>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" placeholder="Telefone" required>
                            </div>
                            <div class="col-lg-12 text-center">
                                <textarea placeholder="Mensagem" required></textarea>
                                <button type="submit" class="site-btn">Enviar Mensagem</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    -->
    <!-- Contact Form Section End -->

    <!-- Contact Section Begin -->
    <?php
    include_once 'app/views/public/default/contact.2.phtml';
    ?>
    <!-- // Contact Section End -->

    <!-- Footer Section Begin -->
    <?php
    include_once 'app/views/public/default/foot.phtml';
    ?>
    <!-- // Footer Section End -->

    <!-- Js Plugins -->
    <?php
    include_once 'app/views/public/default/javascript.phtml';
    ?>
    <!-- // Js Plugins -->
</body>

</html>