<!DOCTYPE html>
<html lang="pt-br">

<head>
    <?php
    include_once 'app/views/public/default/head.phtml';
    ?>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <?php
      include_once 'app/views/public/default/header.phtml';
    ?>
    <!-- Header End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Entenda tudo sobre o festival</h2>
                        <div class="bt-option">
                            <a href="/festival/Home/">Início</a>
                            <span>O Festival</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- About Section Begin -->
    <section class="about-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>FestiAngola 2021</h2>
                        <p class="f-para"><strong>O FestiAngola</strong> é um evento do âmbito nacional organizado pelo <strong>Grupo Boa Vida</strong>, que conta com as produções de <strong>AM Entertainment<strong> e </strong>Top Music Angola</strong>.</p>
                        <p class="para"><strong>O FestiAngola</strong> é o primeiro Festival de Canção dos estilos <strong>Semba</strong>, <strong>Kizomba</strong> e <strong>Kuduro</strong>, de âmbito nacional que visa projectar e lançar novos talentos, podendo nele participar jovens das <strong>18 províncias de Angola</strong> dos <strong>18</strong> aos <strong>35 anos</strong> de idade.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="about-pic">
                        <img src="https://festiangola.co.ao/web-files/assets/img/about-us.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-text">
                        <p class="para">Para a primeira edição, o <strong>FestiAngola</strong> será realizado no dia <strong>17 de Setembro</strong> em <strong>Formato de TV</strong>, tendo como a Cadeia Televisiva Oficial a <strong>TPA</strong>.</p>
                        <p class="para">O <strong>FestiAngola</strong> conta com os apoios institucionais com o <strong>Ministério da Cultura, Turismo e Ambiente, do Ministério das Telecomunicações, Tecnologias de Informação e Comunicação Social</strong>, da <strong>União Nacional dos Compositores de Angola - UNAC</strong> e da <strong>Sociedade dos Direitos de Autor de Angola - SADIA</strong>.</p>
                        <p class="para">Da decisão do Júri não cabe revogação e serão avaliados os seguintes itens:</p>
                        <ul>
                            <li><span class="icon_check"></span> Letra da Canção</li>
                            <li><span class="icon_check"></span> Melodia</li>
                            <li><span class="icon_check"></span> Harmonia</li>
                            <li><span class="icon_check"></span> Afinação</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Section End -->

    <!-- Premiacao Section Begin -->
    <section class="pricing-section set-bg spad" data-setbg="https://festiangola.co.ao/web-files/assets/img/hero.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Prémios</h2>
                        <p></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="price-item">
                        <h4>2º Classificado</h4>
                        <div class="pi-price">
                            <h2><!--<span>Kz</span>-->A anunciar</h2>
                        </div>
                        <ul>
                            <li style="color:#000000;">Certificado de participação</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="price-item top-rated">
                        <div class="tr-tag">
                            <i class="fa fa-star"></i>
                        </div>
                        <h4>1º Classificado</h4>
                        <div class="pi-price">
                            <h2><!--<span>Kz</span>-->A anunciar</h2>
                        </div>
                        <ul>
                            <li style="color:#000000;">Certificado de participação</li>
                        </ul>
                        <a href="/festival/Home/inscricao" class="price-btn">Inscrever-se <span class="arrow_right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="price-item">
                        <h4>3º Classificado</h4>
                        <div class="pi-price">
                            <h2><!--<span>Kz</span>-->A anunciar</h2>
                        </div>
                        <ul>
                            <li style="color:#000000;">Certificado de participação</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Premiacao Section End -->

    <!-- Story Section Begin -->
    <section class="story-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Quem participa?</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="story-left">
                        <div class="story-item">
                            <h2>1</h2>
                            <div class="si-text">
                                <h4></h4>
                                <p class="para">Seão aceites inscrições individuas, duetos e trios com preenchimento de uma Ficha de Inscrição disponível neste site desde 30 de Julho.</p>
                            </div>
                        </div>
                        <div class="story-item">
                            <h2>2</h2>
                            <div class="si-text">
                                <h4></h4>
                                <p class="para">Não é permitido a transferência do lugar de participação em caso de desistência do concorrente inscrito.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="story-right">
                        <div class="story-item">
                            <h2>3</h2>
                            <div class="si-text">
                                <h4></h4>
                                <p class="para">É aceite o cancelamento da inscrição do participante com a notificação da organização para o efeito num prazo não inferior a cinco dias da data após o lançamento do Festival.</p>
                            </div>
                        </div>
                        <div class="story-item">
                            <h2>4</h2>
                            <div class="si-text">
                                <h4></h4>
                                <p class="para">A inscrição do Participante ao Festival valida o Contrato de Adesão cuja concordância é divulgada neste site.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Story Section End -->

    <!-- Juri Section Begin -->
    <?php
    include_once 'app/views/public/default/juri.phtml';
    ?>
    <!-- // Juri Section End -->

    

    <!-- Newslatter Section Begin --
    <section class="newslatter-section about-newslatter">
        <div class="container">
            <div class="newslatter-inner set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/newslatter-bg.jpg">
                <div class="ni-text">
                    <h3>Subscribe Newsletter</h3>
                    <p>Subscribe to our newsletter and don’t miss anything</p>
                </div>
                <form action="#" class="ni-form">
                    <input type="text" placeholder="Your email">
                    <button type="submit">Subscribe</button>
                </form>
            </div>
        </div>
    </section>
    -- Newslatter Section End -->

    <!-- Contact Section Begin -->
    <?php
    include_once 'app/views/public/default/contact.phtml';
    ?>
    <!-- // Contact Section End -->

    <!-- Footer Section Begin -->
    <?php
    include_once 'app/views/public/default/foot.phtml';
    ?>
    <!-- // Footer Section End -->

    <!-- Js Plugins -->
    <?php
    include_once 'app/views/public/default/javascript.phtml';
    ?>
    <!-- // Js Plugins -->
</body>

</html>