<!DOCTYPE html>
<html lang="pt-br">

<head>
    <?php
    include_once 'app/views/public/default/head.phtml';
    ?>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <?php
    include_once 'app/views/public/default/header.phtml';
    ?>
    <!-- // Header End -->
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Regulamento</h2>
                        <div class="bt-option">
                            <a href="/festival/Home/">Início</a>
                            <span>Regulamento</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->


    <!-- Blog Details Hero Section Begin -->
    <!-- Blog Details Hero Section End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 m-auto">
                    <div class="bd-text">
                        <div class="bd-more-text second-text">
                            <h4>1ª Edição Festival da Canção Patriótica </h4>
                            <h4>1. O Festival</h4>
                        </div>
                        <div class="bd-quote">
                            <p style="text-align: justify;">1.1. O <strong>GRUPO BOA VIDA</strong>, no âmbito da sua Política Social, com <strong>Apoio Institucional do MCTA</strong>, vai realizar, nos meses de Agosto e Setembro de 2021, a 1ª Edição do Festival da Canção (Festival da Canção 2021), dirigida essencialmente para Jovens dos 18-35 anos em todo território nacional.</p>
                            <img src="img/quote-left.png" alt="">
                        </div>
                        <div class="bd-quote">
                            <p style="text-align: justify;">1.2. Os Géneros e Estilos são Semba, Kizomba e Kuduro, géneros musicais existentes na nossa diversidade tradicional ou moderna, nas línguas nacionais faladas no nosso país, de modo geral, aquelas que enaltecem os Valores morais e cívicos, valores Sociais, Educativos e Universais.</p>
                            <p style="text-align: justify;">As Canções devem reger-se ou ser inspiradas em Palavras que transmitam princípios e valores Universais como:</p>
                            <p style="text-align: justify;"><strong>- Patriota; Patriotismo, Amor ao Próximo, Solidariedade, Pátria, País, Nação, Família, Pai, Mãe, Irmão, Amigo, Amizade, Fraternidade, Carinho, Ternura, Afeto, Paixão, Compaixão, Proteção, Vida, Doação, Doar, Amar, Respeitar, Natureza, Animais, Plantar, Defender, Defesa, Integridade, Proeza, Alcance, Prestigio, Prestigiar, Nação, integridade, Humanidade, Sociedade, Mulher, Criança, Homem, Salvar, Não a Descriminação, Não ao Odio, Não aos vícios, Não as Drogas, Não a Prostituição, Não a Corrupção, Estudo, Trabalho, Progresso, Conquistas, Juventude, Formação, Inclusão etc.</strong></p>
                            <img src="img/quote-left.png" alt="">
                        </div>
                        <div class="bd-quote">
                            <p style="text-align: justify;">1.3. A Primeira fase:</p>
                            <p style="text-align: justify;">As Canções para o Festival, deverão ser remetidas ao Site até 31 de Agosto de 2021, devendo ser necessário o Preenchimento de uma formulário de Inscrição, onde deve constar:</p>
                            <p style="text-align: justify;"><strong>Nome do artista ou grupo, número do bilhete de identidade do artista ou líder do grupo, província, data de nascimento, sexo, estilo musical e link para download da música Anexado Copia de BI ou outro documento Valido.</strong></p>
                            <p style="text-align: justify;">Podendo também ser possíveL a Inscrições serem feitas a partir das referidas Direcções e Gabinetes Provinciais e Municipais da Cultura, que deverão remeter-nos nos prazos e datas previstas no nosso Regulamento, Sendo possível para as províncias uma tolerância até 2 dias 17 de Agosto de 2021;</p>
                            <p style="text-align: justify;">Obrigatoriamente devem obedecer os Seguintes Critérios ou condições:</p>
                            <div class="about-text">
                                <ul style="color: #000000;">
                                    <li><span class="icon_check"></span> As Canções devem ser Cantadas e Gravada em Estúdio para permitir que tenham condições de áudio audíveis e de fácil percepção;</li>
                                    <li><span class="icon_check"></span> Pode ser gravada acompanhada por um instrumento Musical (Batuques, Guitarra, Piano, ou apenas Por Voz);</li>
                                    <li><span class="icon_check"></span> Com Duração de 4 a 6 minutos;</li>
                                    <li><span class="icon_check"></span> Os candidatos podem participar com apenas uma (1) Canção;</li>
                                    <li><span class="icon_check"></span> Se for Cantada em Línguas Nacionais é Obrigatório a remessa do texto da letra traduzido;</li>
                                    <li><span class="icon_check"></span> São Permitidas a participação de Grupos Corais ou Religiosos; </li>
                                </ul>
                            </div>
                        </div>
                        <div class="bd-quote">
                            <p style="text-align: justify;">1.4. A Segunda Fase:</p>
                            <p style="text-align: justify;">As canções serão avaliadas por um Corpo de Júri integrada por pessoas criteriosamente indicadas para o efeito, devendo merecer o reconhecimento e prestígio a altura dos objetivos e Propósitos definidos, que terá a responsabilidade de escolher as 18 Canções que irão Participar na Gala de consagração Final, que vai homenagear o dia do <strong>Herói Nacional o Saudoso Presidente Dr. António Agostinho Neto</strong> a 17 de Setembro de 2021, elegerá a canção vencedora;</p>
                        </div>
                        <div class="bd-quote">
                            <p style="text-align: justify;">1.5. Quaisquer Duvidas, divergências e/ou conflitos que decorram de situações previstas ou omissas neste regulamento serão rigorosamente analisadas pela Organização do Grupo Boa Vida, cabendo-lhe sempre, enquanto entidade Promotora.</p>
                        </div>

                        <div class="bd-more-text second-text">
                            <h4>2. Disposições Finais</h4>
                        </div>
                        <div class="bd-quote">
                            <p style="text-align: justify;">Para além do Estabelecido, em concreto no Regulamento, caberá ainda a Boa Vida como Promotora, organizadora ser responsável pela criação das condições de Divulgação desta iniciativa ligadas ao Festival da Canção com responsabilidade de Esclarecer, avaliar e decidir sobre qualquer situação que se venha a verificar e que não esteja comtemplada neste regulamento ou, estando, possa gerar quaisquer dúvidas interpretativas.</p>
                            <p style="text-align: justify;">O <strong>Grupo Boa Vida</strong> determinará o Critério a aplicar em qualquer situação não prevista expressamente no Presente regulamento, bem como será a única autoridade interpretativa do mesmo.</p>
                            <p style="text-align: justify;">Para qualquer esclarecimento adicional os contactos devem ser remetidos ao e-mail geral@festiangola.co.ao ou contactos telefónicos: +244 923 698 943 • +244 944 692 347</p>
                            <p style="text-align: justify;">A Participação no Festival da Canção implica a Aceitação integral deste Regulamento.</p>
                        </div>
                        <div class="bd-tag-share">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->

    <!-- Related Post Section Begin -->
    <section class="related-post-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2></h2>
                    </div>
                </div>
            </div>

    </section>
    <!-- Related Post Section End -->

    <!-- Contact Section Begin -->
    <?php
    include_once 'app/views/public/default/contact.phtml';
    ?>
    <!-- // Contact Section End -->

    <!-- Footer Section Begin -->
    <?php
    include_once 'app/views/public/default/foot.phtml';
    ?>
    <!-- // Footer Section End -->

    <!-- Js Plugins -->
    <?php
    include_once 'app/views/public/default/javascript.phtml';
    ?>
    <!-- // Js Plugins -->
</body>

</html>