<section class="schedule-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Nossa Agenda</h2>
                    <p>Conheça o nosso cronograma</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="schedule-tab">
                    <?php
                    if (isset($v_agendas)) {
                        if (empty($v_agendas)) {
                    ?>
                            <div class="alert alert-danger">
                                <strong><span class="fa fa-info"></span></strong> Até o momento não temos nada agendado.
                            </div>
                    <?php
                        }
                        foreach ($v_agendas as $agenda) {
                        }
                    } ?>
                    <ul class="nav nav-tabs" role="tablist">
                        <?php
                        if (isset($v_agendas)) {
                            $cont = 0;
                            foreach ($v_agendas as $datas) {
                                ++$cont;
                                if (($cont) == 1) {
                        ?>
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="tab" href="#tabs-<?= $datas->getId() ?>" role="tab">
                                            <h5>Data</h5>
                                            <p><?= $datas->getData() ?></p>
                                        </a>
                                    </li>
                                <?php
                                } else {
                                ?>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#tabs-<?= $datas->getId() ?>" role="tab">
                                            <h5>Data</h5>
                                            <p><?= $datas->getData() ?></p>
                                        </a>
                                    </li>
                                <?php
                                }
                                ?>

                        <?php
                            }
                        } ?>


                    </ul><!-- Tab panes -->
                    <div class="tab-content">
                        <?php
                        if (isset($v_agendas)) {
                            $contt = 0;
                            foreach ($v_agendas as $descricoes) {
                                ++$contt;
                                if (($contt) == 1) {
                        ?>

                                    <div class="tab-pane active" id="tabs-<?= $descricoes->getId() ?>" role="tabpanel">
                                        <div class="st-content">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-lg-3">
                                                        <div class="sc-pic">
                                                            <img src="https://festiangola.co.ao/web-files/assets/img/schedule/schedule-1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-5">
                                                        <div class="sc-text">
                                                            <h4><?= $descricoes->getDescricao() ?></h4>
                                                            <ul>
                                                                <li><i class="fa fa-map-marker"></i> <?= $descricoes->getLocal() ?></li>
                                                                <li><i class="fa fa-clock-o"></i> <?= $descricoes->getHora() ?></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                <?php
                                } else {
                                ?>
                                    <div class="tab-pane" id="tabs-<?= $descricoes->getId() ?>" role="tabpanel">
                                        <div class="st-content">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-lg-3">
                                                        <div class="sc-pic">
                                                            <img src="https://festiangola.co.ao/web-files/assets/img/schedule/schedule-1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-5">
                                                        <div class="sc-text">
                                                            <h4><?= $descricoes->getDescricao() ?></h4>
                                                            <ul>
                                                                <li><i class="fa fa-map-marker"></i> <?= $descricoes->getLocal() ?></li>
                                                                <li><i class="fa fa-clock-o"></i> <?= $descricoes->getHora() ?></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                <?php
                                }
                                ?>

                        <?php
                            }
                        } ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>