<section class="contact-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">

                <div class="section-title">
                    <h2>FestiAngola 2021</h2>
                    <p></p>
                </div>
                <div class="cs-text">
                    <div class="ct-address">
                        <span>Endereço:</span>
                        <p>Urbanização Boa Vida<br />Luanda</p>
                    </div>
                    <ul>
                        <li>
                            <span>Telefones:</span>
                            +244 923 698 943
                        </li>
                        <li>
                            <span>Email:</span>
                            geral@festiangola.co.ao
                        </li>
                    </ul>
                    <div class="ct-links">
                        <span>Website:</span>
                        <p>https://festiangola.co.ao</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="cs-map">
                    <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3940.970528513714!2d13.214864114786193!3d-8.974858893558443!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1a521f28dbf07e05%3A0xc1b45c57d9661cff!2sUrbaniza%C3%A7%C3%A3o%20Boa%20Vida!5e0!3m2!1spt-PT!2sao!4v1627476924930!5m2!1spt-PT!2sao"
                            height="400" style="border:0;" allowfullscreen=""></iframe>
                </div>
            </div>
            <img src="https://festiangola.co.ao/web-files/assets/img/sponsors.jpg" style="width: 100%;">
        </div>
    </div>
</section>