<footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-text">
                        <div class="ft-logo">
                            <a href="/Index/" class="footer-logo"><img src="https://festiangola.co.ao/web-files/assets/img/footer-logo.png" alt=""></a>
                        </div>
                        <ul>
                            <li><a href="/Index/">Início</a></li>
                            <li><a href="/Index/festival">O Festival</a></li>
                            <li><a href="/Index/regulamento">Regulamento</a></li>
                            <li><a href="/Index/contacto">Contactos</a></li>
                        </ul>
                        <div class="copyright-text">
                            <p>
                                FestiAngola &copy; <?php echo date('Y'); ?> &bull; Todos os direitos reservados<br>
                                <a style="font-size:12px;" href="https://mrvipaji.ao" target="_blank">MR. VIPAJI <i class="fa fa-heart" aria-hidden="true"></i> Quizá, el mejor del mundo</a>
                            </p>
                        </div>
                        <div class="ft-social">
                            <a href="https://www.facebook.com/FestiAngolaAO/" target="_blank"><i class="fa fa-facebook"></i></a>
                            <!--<a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>