<meta charset="UTF-8">
<meta name="description" content="FestiAngola, FestiAngola 21, FestiAngola 2021, FestiAngola Angola, Festival, Kuduro, Semba, Kizomba, FestiAngola Cultura">
<meta name="keywords" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

<!-- This site is optimized with the Yoast SEO plugin v6.3.1 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="description" content="O FestiAngola é um evento do âmbito nacional organizado pelo Grupo Boa Vida, que conta com as produções de AM Entertainment e Top Music Angola." />
<meta property="og:locale" content="pt_PT" />
<meta property="og:type" content="website" />
<meta property="og:title" content="FestiAngola 2021&#8482; - Festival Nacional da Canção Patriótica" />
<meta property="og:description" content="O FestiAngola é um evento do âmbito nacional organizado pelo Grupo Boa Vida, que conta com as produções de AM Entertainment e Top Music Angola." />
<meta property="og:url" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<meta property="og:site_name" content="FestiAngola 2021&#8482; - Festival Nacional da Canção Patriótica" />
<meta property="og:image" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<meta property="og:image:secure_url" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<meta name="google:card" content="summary_large_image" />
<meta name="google:description" content="O FestiAngola é um evento do âmbito nacional organizado pelo Grupo Boa Vida, que conta com as produções de AM Entertainment e Top Music Angola." />
<meta name="google:title" content="FestiAngola 2021&#8482; - Festival Nacional da Canção Patriótica" />
<meta name="google:image" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<!-- // SEO-->

<!-- Favicons -->
<link rel="icon" href="https://festiangola.co.ao/web-files/assets/img/footer-logo.png" type="image/ico" />

<title><?= $v_title_page; ?></title>

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


<!-- Css Styles -->
<link rel="stylesheet" href="https://festiangola.co.ao/web-files/assets/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="/web-files/assets/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="/web-files/assets/css/elegant-icons.css" type="text/css">
<link rel="stylesheet" href="https://festiangola.co.ao/web-files/assets/css/owl.carousel.min.css" type="text/css">
<link rel="stylesheet" href="https://festiangola.co.ao/web-files/assets/css/magnific-popup.css" type="text/css">
<link rel="stylesheet" href="https://festiangola.co.ao/web-files/assets/css/slicknav.min.css" type="text/css">
<link rel="stylesheet" href="https://festiangola.co.ao/web-files/assets/css/style.css" type="text/css">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9G22G12GG6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9G22G12GG6');
</script>