<script src="https://festiangola.co.ao/web-files/assets/js/jquery-3.3.1.min.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/bootstrap.min.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/jquery.magnific-popup.min.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/jquery.countdown.min.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/jquery.slicknav.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/owl.carousel.min.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/main.js"></script>
<script src="https://festiangola.co.ao/web-files/assets/js/inscricao.js"></script>