<section class="team-member-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Corpo de Jurados</h2>
                    <p>Conheça quem uniu-se ao Projecto</p>
                </div>
            </div>
        </div>
    </div>
    <div class="member-item set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/team-member/member-1.jpg">
        <div class="mi-social">
            <!--
                <div class="mi-social-inner bg-gradient">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            -->
        </div>
        <div class="mi-text">
            <h5>Euclides da Lomba</h5>
            <span>Músico</span>
        </div>
    </div>
    <div class="member-item set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/team-member/member-2.jpg">
        <div class="mi-social">
            <!--
                <div class="mi-social-inner bg-gradient">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            -->
        </div>
        <div class="mi-text">
            <h5>Carlos Lamartine</h5>
            <span>Músico</span>
        </div>
    </div>
    <div class="member-item set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/team-member/member-md.jpg">
        <div class="mi-social">
                <div class="mi-social-inner bg-gradient">
                    <!--<a href="https://www.facebook.com/fabiodance1"><i class="fa fa-facebook"></i></a>-->
                    <a href="https://www.instagram.com/rosariomargarethdo/"><i class="fa fa-instagram"></i></a>
                    <!--<a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>-->
                </div>
        </div>
        <div class="mi-text">
            <h5>Margareth do Rosário</h5>
            <span>Músico</span>
        </div>
    </div>
    <div class="member-item set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/team-member/member-4.jpg">
        <div class="mi-social">
            <div class="mi-social-inner bg-gradient">
                <!--<a href="https://www.facebook.com/fabiodance1"><i class="fa fa-facebook"></i></a>-->
                <a href="https://www.instagram.com/official_fabiodance/"><i class="fa fa-instagram"></i></a>
                <!--<a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>-->
            </div>
        </div>
        <div class="mi-text">
            <h5>Fábio Dance</h5>
            <span>Músico</span>
        </div>
    </div>
    <div class="member-item set-bg" data-setbg="https://festiangola.co.ao/web-files/assets/img/team-member/member-5.jpg">
        <div class="mi-social">
            <div class="mi-social-inner bg-gradient">
                <a href="https://www.facebook.com/Kletuzoficial/"><i class="fa fa-facebook"></i></a>
                <a href="https://www.instagram.com/kletuz_oficial/"><i class="fa fa-instagram"></i></a>
                <!--<a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>-->
            </div>
        </div>
        <div class="mi-text">
            <h5>Kletuz</h5>
            <span>Músico</span>
        </div>
    </div>

</section>