<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Actualizar Veículo</h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->

            <div class="col-6">
              <div class="card">

              <form role="form" id="formPerfil" method="POST" action="<?= $v_page_url;?>actualizar">
                <div class="card-body">
                  <div class="form-group">
                    <label for="marca">Marca</label>
                    <select id="marca" name="marca" class="form-control" required>
                    <?php
                      $v_marcas = (isset($v_marcas) ? ($v_marcas) : (array()));
                        foreach ($v_marcas as $marca) {
                          echo '<option value="' . $marca->getId() . '" ' . ($marca->getId() == $v_entity->getMarca()->getId() ? 'selected' : '') . '>' . ucfirst(Method::lowerGeneral($marca->getNome())) . '</option> ';
                        }
                    ?>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="modelo">Modelo</label>
                    <input type="text" name="modelo" required class="form-control" id="modelo" placeholder="modelo" value="<?= $v_entity->getModelo(); ?>">
                  </div>
                  <div class="form-group">
                    <label for="matricula">Matrícula</label>
                    <input type="text" name="matricula" required class="form-control" id="matricula" placeholder="matricula" value="<?= $v_entity->getMatricula(); ?>">
                  </div>
                  <div class="form-group">
                    <label for="num_motor">N.º Chassi</label>
                    <input type="text" name="num_motor" required class="form-control" id="num_motor" placeholder="N.º Chassi" value="<?= $v_entity->getNumMotor(); ?>">
                  </div>
                  <div class="form-group">
                    <label for="cor">Cor</label>
                    <select id="cor" name="cor" class="form-control" required>
                      <option value="Branca">Branca</option>
                      <option value="Preta">Preta</option>
                      <option value="Cinzenta">Cinzenta</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="combustivel">Combustível</label>
                    <select id="combustivel" name="combustivel" class="form-control" required>
                      <option value="Gasóleo">Gasóleo</option>
                      <option value="Gasolina">Gasolina</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="data_registo">Data 1º Registo</label>
                    <input type="date" name="data_registo" required class="form-control" id="data_registo" placeholder="Data 1º Registo" value="<?= $v_entity->getDataRegisto(); ?>">
                    <input type="hidden" name="id_veiculo" value="<?= $v_entity->getID(); ?>">
                  </div>
                  
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Actualizar <?= $v_page_context;?></button>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <a href="#" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i
                        class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                  </div>
                </div>
              </form>
              </div>
            </div>
            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>
    
  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
  ?>
</body>
</html>