<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page;?></title>

  <?php
    include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
      include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
        include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context;?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            <!-- / Corpo da página INÍCIO -->
            <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title"></h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" id="formVeiculo" method="POST" action="<?= $v_page_url;?>registar">
                <div class="card-body">
                  <div class="form-group">
                    <label for="marcca">Marca</label>
                    <select id="marca" name="marca" required class="form-control">
                      <option value="" selected="">---</option>
                        <?php
                          $v_marcas = (isset($v_marcas) ? ($v_marcas) : (array()));
                          foreach ($v_marcas as $marca) {
                            echo '<option value="' . $marca->getId() . '">' . ucfirst(Method::lowerGeneral($marca->getNome())) . '</option> ';
                          }
                        ?>
                      </select>
                  </div>
                  <div class="form-group">
                    <label for="modelo">Modelo</label>
                    <input type="text" name="modelo" class="form-control" required id="modelo" placeholder="Modelo">
                  </div>
                  <div class="form-group">
                    <label for="matricula">Matrícula</label>
                    <input type="text" name="matricula" class="form-control" required id="matricula" placeholder="Matrícula">
                  </div>
                  <div class="form-group">
                    <label for="num_motor">N.º Chassi</label>
                    <input type="text" name="num_motor" class="form-control" required id="num_motor" placeholder="N.º Chassi">
                  </div>
                  <div class="form-group">
                    <label for="cor">Cor</label>
                    <select id="cor" name="cor" class="form-control" required>
                      <option value="" selected="">---</option>
                      <option value="Branca">Branca</option>
                      <option value="Preta">Preta</option>
                      <option value="Cinzenta">Cinzenta</option>
                      <option value="Pérola">Pérola</option>
                      <option value="Vermelha">Vermelha</option>
                      <option value="Azul">Azul</option>
                      <option value="Verde">Verde</option>
                      <option value="Amarela">Amarela</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="combustivel">Combustível</label>
                    <select id="combustivel" name="combustivel" class="form-control" required>
                      <option value="" selected="">---</option>
                      <option value="Gasóleo">Gasóleo</option>
                      <option value="Gasolina">Gasolina</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="data_registo">Data 1º Registo</label>
                    <input type="date" name="data_registo" required class="form-control" id="data_registo" placeholder="data_registo">
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Gravar</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
            
            <!-- / Corpo da página FIM -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>
    
  </div>
  <!-- ./wrapper -->

  <?php
    include_once 'app/views/public/adm/javascript.phtml';
    include_once 'app/views/public/adm/datatables.phtml';
  ?>
  <script type="text/javascript">
$(document).ready(function () {
  $.validator.setDefaults({
  });
  $('#formVeiculo').validate({
    rules: {
      nome: {
        required: true
      },
      descricao: {
        required: true,
        minlength: 10
      },
      terms: {
        required: true
      },
    },
    messages: {
      nome: {
        required: "Por favor, insira o nome da escola"
      },
      descricao: {
        required: "É necessário que descreva a escola para melhor detalhes",
        minlength: "Descrição é muito curtaa. Deve ter mais de 10 caracteres."
      }
      /*,
      terms: "Please accept our terms"*/
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
});
</script>
</body>
</html>