<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title><?= $v_title_page; ?></title>

  <?php
  include_once 'app/views/public/adm/head.phtml';
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <?php
    include_once 'app/views/public/adm/topNavigation.phtml';
    ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar elevation-4 sidebar-light-indigo">

      <!-- Brand Logo -->
      <?php
      include_once 'app/views/public/adm/logo.phtml';
      ?>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <?php
        include_once 'app/views/public/adm/userInfo.phtml';
        ?>
        <!-- Sidebar Menu -->
        <?php
        include_once 'app/views/public/menuLateral.phtml';
        ?>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark"><?= $v_page_context; ?></h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <form role="form" id="formAcessorio" method="POST" action="<?= $v_page_url; ?>actualizar">
            <div class="row">
              <!-- / Corpo da página INÍCIO -->

              <div class="col-6">

                <div class="card">

                  <div class="card-body">
                    <div class="form-group">
                      <label for="titulo-blog">Título</label>
                      <input type="hidden" value="<?= $v_entity->getID(); ?>" name="id_blog">
                      <input type="text" name="titulo" class="form-control" id="titulo-blog" placeholder="Título" value="<?= $v_entity->getTitulo() ?>">
                    </div>
                    <div class="form-group">
                      <label for="texto-blog">Conteúdo</label>
                      <textarea name="texto" class="form-control" id="texto-blog" rows="8" placeholder="Conteúdo"><?= $v_entity->getTexto() ?></textarea>
                    </div>
                    <div class="form-group">
                      <label for="estado-<?= $v_page_context; ?>">Estado</label>
                      <select id="estado-<?= $v_page_context; ?>" name="estado" class="form-control" required="">
                        <?php
                        echo '<option value="' . Geral::CONS_BLOG_PUBLICADO . '" ' . (Geral::CONS_BLOG_PUBLICADO == $v_entity->getEstado() ? 'selected' : '') . '>Publicado</option> ';
                        echo '<option value="' . Geral::CONS_BLOG_N_PUBLICADO . '" ' . (Geral::CONS_BLOG_N_PUBLICADO == $v_entity->getEstado() ? 'selected' : '') . '>Não publicado</option> ';
                        ?>
                      </select>
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <!--<div class="card-footer">
                  <button type="submit" class="btn btn-primary">Gravar <?= $v_page_context; ?></button>
                </div>-->
                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <a style="cursor:pointer" onclick="voltar();" class="btn btn-default btn-circle" title="Voltar"><i class="fa fa-chevron-left"></i><strong> Voltar</strong></a>
                      <button type="submit" class="btn btn-primary">Actualizar <?= $v_page_context; ?></button>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-6">
                <div class="card">
                  <div class="card-body">
                    <?php
                    if (isset($v_entity)) {
                      $foto = $v_entity->getFoto();
                      if (!$v_entity->getFoto() == null) {
                        echo '<img class="img-fluid" src="' . Geral::DIR_IMG_BLOG . $foto . '" alt="Foto de ' . $v_entity->getTitulo() . '" title="Foto de ' . $v_entity->getTitulo() . '" />';
                      } else {
                      }
                    }
                    ?>
                  </div>
                </div>
              </div>
              <!-- / Corpo da página FIM -->
            </div>
          </form>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <?php
    include_once 'app/views/public/adm/foot.phtml';
    ?>

  </div>
  <!-- ./wrapper -->

  <?php
  include_once 'app/views/public/adm/javascript.phtml';
  include_once 'app/views/public/adm/datatables.phtml';
  ?>
  <script type="text/javascript">
    $(document).ready(function() {
      $.validator.setDefaults({});
      $('#formBlog').validate({
        rules: {
          titulo: {
            required: true
          },
          texto: {
            required: true,
            minlength: 250
          },
          terms: {
            required: true
          },
        },
        messages: {
          titulo: {
            required: "Por favor, insira o título da publicação."
          },
          texto: {
            required: "É necessário que descreva a publicação para melhor detalhes",
            minlength: "O conteúdo é muito curto. Deve ter mais de 250 caracteres."
          }
          /*,
          terms: "Please accept our terms"*/
        },
        errorElement: 'span',
        errorPlacement: function(error, element) {
          error.addClass('invalid-feedback');
          element.closest('.form-group').append(error);
        },
        highlight: function(element, errorClass, validClass) {
          $(element).addClass('is-invalid');
        },
        unhighlight: function(element, errorClass, validClass) {
          $(element).removeClass('is-invalid');
        }
      });
    });

    function voltar() {
      window.history.back();
    }
  </script>
</body>

</html>