    <!-- SEO -->
<!-- This site is optimized with the Yoast SEO plugin v6.3.1 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="description" content="O FestiAngola é um evento do âmbito nacional organizado pelo Grupo Boa Vida, que conta com as produções de AM Entertainment e Top Music Angola." />
<meta property="og:locale" content="pt_PT" />
<meta property="og:type" content="website" />
<meta property="og:title" content="FestiAngola 2021&#8482; - Festival Nacional da Canção Patriótica" />
<meta property="og:description" content="O FestiAngola é um evento do âmbito nacional organizado pelo Grupo Boa Vida, que conta com as produções de AM Entertainment e Top Music Angola." />
<meta property="og:url" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<meta property="og:site_name" content="FestiAngola 2021&#8482; - Festival Nacional da Canção Patriótica" />
<meta property="og:image" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<meta property="og:image:secure_url" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<meta name="google:card" content="summary_large_image" />
<meta name="google:description" content="O FestiAngola é um evento do âmbito nacional organizado pelo Grupo Boa Vida, que conta com as produções de AM Entertainment e Top Music Angola." />
<meta name="google:title" content="FestiAngola 2021&#8482; - Festival Nacional da Canção Patriótica" />
<meta name="google:image" content="https://festiangola.co.ao/web-files/assets/img/logo_seo.png" />
<!-- // SEO-->
<!--===============================================================================================-->
<!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/web-files/adm/plugins/fontawesome-free/css/all.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="https://festiangola.co.ao/web-files/adm/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="https://festiangola.co.ao/web-files/adm/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">