<?php
    if(strtolower($v_userInfo->getPerfil()->getNome()) == Geral::CONS_PERFIL_ADMINISTRADOR)
    {
        include_once 'menu/administrador.phtml';
    }
    /*else if(strtolower($v_userInfo->getPerfil()->getNome()) == Geral::CONS_PERFIL_GESTOR)
    {
        include_once 'menu/administrador.phtml';
    }*/
    else if(strtolower($v_userInfo->getPerfil()->getNome()) == Geral::CONS_PERFIL_OPERADOR)
    {
        include_once 'menu/operador.phtml';
    }
?>